### ISSUE TITLE
Player running animations still occuring even after latest commit.

### ISSUE THREAD

**Issue by grumpybee100** [Grumpy-Games-Studios/run#2] opened 2017-11-03 07:36 UTC
Weird. Even though we last tested it out to be working fine, the player's run animations keep conflicting along with the player's still animations(double occurrence of animations). Would want @grumpycoder100 to see this out ASAP.

**Comment by grumpycoder100** [comment] 2017-11-03 07:39
I'm already on it. Though I actually found this out already this morning. I removed the **async** code and am rewriting the touch events that involves the triggering of player's animations. Will update ASAP.

**Comment by grumpycoder100** [comment] 2017-11-04 10:20
Hey @grumpybee100 . I've managed to find the cause of the animations. There are too many conflicting events that tend to trigger the different animations at the same time of user input. I'll do the commit by tonight. Got some help from @grumpyspaceman100 for testing everything out.

**Comment by grumpybee100** [comment] 2017-11-04 11:49
Great to hear this! Do close this issue after you do the commit. Thanks!

**Comment by grumpycoder100** [comment] 2017-11-04 12:02
Fixed in latest commit 8750220

**Closed by grumpycoder100** 2017-11-04 12:02 UTC
Labels: bug
